[2023-04-11 10:22:40,118] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:22:40] "[35m[1mPOST /interacao HTTP/1.1[0m" 500 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:01,896] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.25:5002 (Press CTRL+C to quit) - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:03,498] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:03] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:03,511] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:03] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:03,603] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:03] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:03,610] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:03] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:03,612] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:03] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:04,345] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:04] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:04,363] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:04] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:04,364] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:04] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:04,365] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:04] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:04,515] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:04] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:28:13,748] ERROR log_exception() L1449 Exception on /interacao [POST] - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py", line 163, in add_interacao
    interacao = Interacao(texto)
TypeError: __init__() missing 1 required positional argument: 'texto'
[2023-04-11 10:28:13,757] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:28:13] "[35m[1mPOST /interacao HTTP/1.1[0m" 500 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:29:05,837] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:29:05] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:29:43,532] WARNING del_previsao() L136  Erro ao deletar previsao #'maresias', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L136 
[2023-04-11 10:29:43,536] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:29:43] "[33mDELETE /previsao?nome_praia=maresias HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:30:01,097] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:30:01] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:30:15,761] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:30:15] "DELETE /previsao?nome_praia=Maresias HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 10:30:23,294] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 10:30:23] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:20:55,603] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.25:5002 (Press CTRL+C to quit) - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:20:57,042] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:20:57] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:20:57,059] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:20:57] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:20:57,154] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:20:57] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:20:57,155] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:20:57] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:20:57,156] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:20:57] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:20:57,167] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:20:57] "GET /openapi/static/images/apidoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:21:05,951] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:21:05] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:21:05,975] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:21:05] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:21:05,980] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:21:05] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:21:05,982] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:21:05] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-17 10:21:06,128] INFO _log() L224  127.0.0.1 - - [17/Apr/2023 10:21:06] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
